
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    command: ["/wait-for-it.sh", "db:5432", "--", "python", "app.py"]
    ports:
      - "5000:5000" 
    environment:
      DB_HOST: db       
      DB_PORT: 5432
      DB_NAME: tododb
      DB_USER: todo
      DB_PASSWORD: todo
      COUNTDOWN_TO_WHORES_ARRIVE: 3 hours
    volumes:
      - .:/app
      

  frontend:
    build: ./frontend
    restart: always
    depends_on:
      - app
      - db 
    ports:
      - "3000:3000"  
    environment:
      REACT_APP_API_URL: http://app:5000/api 
    

volumes:
  pgdata:
